---
title: "Rmarkdown citi bikes analysis"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Citi bikes data

Zip archive for all cvs files (up to August 2020): <https://www.dropbox.com/s/wg4gncn6sx5v82i/import_citibikes.zip?dl=0>
How I scrapped all of them: see extracting_files.sh (just a text file with R code)

## Data merging
Will take March-August 2019 and 2020 for now

```{r packages, echo=TRUE, message=FALSE, warning=FALSE}
# packages to load or download and load
pkgs = c("dplyr","ggplot2","tidyverse","readr","janitor","data.table") # packages names
#install.packages(pkgs) # can omit if already installed
inst = lapply(pkgs, library, character.only = TRUE) # load them
```

Loading selected csv and merging in one dataframe
```{r merging, message=FALSE, warning=FALSE, dev=c('png', 'pdf'), eval=FALSE}
#library(readr)
files <- list.files(path = "/Users/shlyuevd/Dropbox/WORKSHOPS/DS4A/import_citibikes",
                    pattern = glob2rx("2019*csv"), 
                    full.names = T)

combined_2019 <- rbindlist(lapply(files, fread))

files <- list.files(path = "/Users/shlyuevd/Dropbox/WORKSHOPS/DS4A/import_citibikes",
                    pattern = glob2rx("2020*csv"), 
                    full.names = T)
combined_2020 <- rbindlist(lapply(files, fread))

combined_2019_2020 <- rbind(combined_2019, combined_2020)
combined_2019_2020_clean <- janitor::clean_names(combined_2019_2020)
saveRDS(combined_2019_2020_clean,"/Users/shlyuevd/Dropbox/WORKSHOPS/DS4A/import_citibikes/tibble_2019_2020_clean.rds")
# saving the CSV
fwrite(combined_2019_2020_clean, "/Users/shlyuevd/Dropbox/combined_2019_2020_clean.csv") 
```

loading RDS with cleaned 2019_2020 data and subseting based on year (March-August)
```{r loading, echo=TRUE, dev=c('png', 'pdf'), message=FALSE, warning=FALSE, eval=F}
tbl_2020_clean <- readRDS("/Users/shlyuevd/Dropbox/WORKSHOPS/DS4A/import_citibikes/tibble_2019_2020_clean.rds")

# splitting starting date and time: need it to split 2020 and 2019 data
tbl_2020_clean$startDate <- as.Date(tbl_2020_clean$starttime) 
# do not need time for now
#tbl_2020_clean$startTime <- format(as.POSIXct(tbl_2020_clean$starttime), format = "%H:%M:%S") 

# getting top start stations in March-August 2019 vs 2020
tbl_2019 <- subset(tbl_2020_clean, startDate > as.Date("2019-03-01") & startDate < as.Date("2019-08-31")) %>% 
            select(-tripduration,-starttime,-stoptime,-start_station_id,-end_station_id, -bikeid, -usertype,-birth_year,-gender, -startDate)
saveRDS(tbl_2019,"/Users/shlyuevd/Dropbox/WORKSHOPS/DS4A/import_citibikes/tibble_2019_test_for_map.rds")

tbl_2020 <- subset(tbl_2020_clean, startDate > as.Date("2020-03-01") & startDate < as.Date("2020-08-31")) %>%
            select(-tripduration,-starttime,-stoptime,-start_station_id,-end_station_id, -bikeid, -usertype,-birth_year,-gender, -startDate)
saveRDS(tbl_2020,"/Users/shlyuevd/Dropbox/WORKSHOPS/DS4A/import_citibikes/tibble_2020_test_for_map.rds")

```
Top start station in 2019 and 2020

```{r top_stations, echo=TRUE, dev=c('png', 'pdf'), message=FALSE, warning=FALSE}
tbl_2020 <- readRDS("/Users/shlyuevd/Dropbox/WORKSHOPS/DS4A/import_citibikes/tibble_2020_test_for_map.rds")
tbl_2019 <- readRDS("/Users/shlyuevd/Dropbox/WORKSHOPS/DS4A/import_citibikes/tibble_2019_test_for_map.rds")

tbl_2019 %>% count(start_station_name, sort=TRUE) %>% head(10)
tbl_2020 %>% count(start_station_name, sort=TRUE) %>% head(10)
```










